import { SignIn, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
// import Link from "next/link";

import { api } from "~/utils/api";

interface UseUserType {
  isLoaded: boolean;
  isSignedIn: boolean;
  user: { id: string };
}

export default function Home() {
  const { isSignedIn, user } = useUser() as UseUserType;
  // const hello = api.post.hello.useQuery({ text: "from tRPC" });
  const {data} = api.event.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App Testing</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          {!isSignedIn && <SignIn/>}
          {!!isSignedIn && <SignOutButton/>}
          <div>
            {data?.map((e)=>(
              <div key={e.id}>
                {e.content}
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
