import { SignIn, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import { Button } from "~/components/ui/button";
import ProfileImage from "~/components/ui/profileImage";

// import Link from "next/link";

import { api } from "~/utils/api";

interface UseUserType {
  isLoaded: boolean;
  isSignedIn: boolean;
  user: { id: string };
}

export default function Home() {
  const { isSignedIn, user } = useUser() as UseUserType;
  // const hello = api.post.hello.useQuery({ text: "from tRPC" });
  const {data, isLoading} = api.event.getAll.useQuery();

  if (isLoading) return (<div>Loading....</div>)
  if (!data) return (<div>Something went wrong!</div>)
  return (
    <>
      <Head>
        <title>Create T3 App Testing</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen">
        <div className="flex min-h-screen flex-col items-center justify-center bg-background">
          {!isSignedIn && <SignIn/>}
          {!!isSignedIn && <Button variant="secondary"> <SignOutButton/></Button>}
          {!!isSignedIn && <ProfileImage/>}
          
          {/* <div>
            {data?.map((e)=>(
              <div key={e.id}>
                {e.content}
              </div>
            ))}
          </div> */}
        </div>
      </main>
    </>
  );
}
